[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @lafineequipe/server build"]

[start]
cmd = "pnpm --filter @lafineequipe/server start"
